/**
 * Frame que va a agregar o modificar una canción de acuerdo a la opción 
 * ingresada. Además lo va a almacenar en una lista.
 */
package musictecplayer.vistas;

/**
 * @author Lucia  Solis
 * @author Joseph Vega
 * @author Miller Ruiz
 */
public class DetalleCancion extends javax.swing.JFrame {

    /**
     * Creates new form DetalleCancion
     */
    public DetalleCancion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFondoPrincipal = new javax.swing.JLabel();
        jLabelFondoOpcion1 = new javax.swing.JLabel();
        jLabelOpcion1 = new javax.swing.JLabel();
        jLabelFondoOperacion = new javax.swing.JLabel();
        jLabelOpcion2 = new javax.swing.JLabel();
        jPanelGeneral = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelFondoOpcion2 = new javax.swing.JLabel();
        jLabelOperacion1 = new javax.swing.JLabel();
        jLabelOperacion2 = new javax.swing.JLabel();

        jLabelFondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Canción");
        setResizable(false);

        jLabelFondoOpcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N

        jLabelOpcion1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelOpcion1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpcion1.setText("General");

        jLabelFondoOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFondoOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N

        jLabelOpcion2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelOpcion2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpcion2.setText("Detalles");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelFondoOpcion2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFondoOpcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N

        jLabelOperacion1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelOperacion1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelOperacion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOperacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperacion1.setText("Aceptar");

        jLabelOperacion2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelOperacion2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelOperacion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOperacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperacion2.setText("Cancelar");
        jLabelOperacion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelOperacion2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelFondoOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelFondoOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOperacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jLabelFondoOperacion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFondoOpcion1)
                    .addComponent(jLabelFondoOperacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOpcion1)
                            .addComponent(jLabelOpcion2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOperacion1)
                            .addComponent(jLabelOperacion2)))
                    .addComponent(jLabelFondoOpcion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelFondoOpcion1.getAccessibleContext().setAccessibleParent(this);

        getAccessibleContext().setAccessibleName("DetalleCanción");

        setSize(new java.awt.Dimension(666, 333));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelOperacion2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOperacion2MouseReleased
        this.hide();
        super.enable();
    }//GEN-LAST:event_jLabelOperacion2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DetalleCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondoOpcion1;
    private javax.swing.JLabel jLabelFondoOpcion2;
    private javax.swing.JLabel jLabelFondoOperacion;
    private javax.swing.JLabel jLabelFondoPrincipal;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelOpcion1;
    private javax.swing.JLabel jLabelOpcion2;
    private javax.swing.JLabel jLabelOperacion1;
    private javax.swing.JLabel jLabelOperacion2;
    private javax.swing.JPanel jPanelGeneral;
    // End of variables declaration//GEN-END:variables
}
