/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package musictecplayer.vistas;

/**
 *
 * @author RUBEN
 */
public class PanelCancion extends javax.swing.JPanel {

    /**
     * Creates new form PanelCancion
     */
    public PanelCancion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenCancion = new javax.swing.JLabel();
        jLabelCacion = new javax.swing.JLabel();
        jLabelNombreAlbum = new javax.swing.JLabel();
        jLabelArtista = new javax.swing.JLabel();
        jLabelNombreAlbum1 = new javax.swing.JLabel();
        jLabelAlbum = new javax.swing.JLabel();
        jLabelNombreAlbum2 = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelNombreAlbum3 = new javax.swing.JLabel();
        jLabelNombreAlbum4 = new javax.swing.JLabel();
        jLabelAño = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(305, 400));
        setLayout(null);

        jLabelImagenCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/caratulas/prince royce.jpg"))); // NOI18N
        jLabelImagenCancion.setToolTipText("");
        add(jLabelImagenCancion);
        jLabelImagenCancion.setBounds(60, 10, 170, 170);

        jLabelCacion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelCacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCacion.setText("Canción:");
        add(jLabelCacion);
        jLabelCacion.setBounds(20, 190, 60, 20);

        jLabelNombreAlbum.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelNombreAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreAlbum.setText("________________");
        add(jLabelNombreAlbum);
        jLabelNombreAlbum.setBounds(80, 190, 150, 20);

        jLabelArtista.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelArtista.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtista.setText("Artista");
        add(jLabelArtista);
        jLabelArtista.setBounds(20, 230, 60, 20);

        jLabelNombreAlbum1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelNombreAlbum1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreAlbum1.setText("________________");
        add(jLabelNombreAlbum1);
        jLabelNombreAlbum1.setBounds(80, 230, 150, 20);

        jLabelAlbum.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelAlbum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlbum.setText("Álbum:");
        add(jLabelAlbum);
        jLabelAlbum.setBounds(20, 270, 60, 20);

        jLabelNombreAlbum2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelNombreAlbum2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreAlbum2.setText("________________");
        add(jLabelNombreAlbum2);
        jLabelNombreAlbum2.setBounds(80, 270, 150, 20);

        jLabelGenero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Género:");
        add(jLabelGenero);
        jLabelGenero.setBounds(20, 310, 60, 20);

        jLabelNombreAlbum3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelNombreAlbum3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreAlbum3.setText("________________");
        add(jLabelNombreAlbum3);
        jLabelNombreAlbum3.setBounds(80, 310, 150, 20);

        jLabelNombreAlbum4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelNombreAlbum4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreAlbum4.setText("________________");
        add(jLabelNombreAlbum4);
        jLabelNombreAlbum4.setBounds(80, 350, 150, 20);

        jLabelAño.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelAño.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAño.setText("Año:");
        add(jLabelAño);
        jLabelAño.setBounds(20, 350, 60, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelAño;
    private javax.swing.JLabel jLabelCacion;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelImagenCancion;
    private javax.swing.JLabel jLabelNombreAlbum;
    private javax.swing.JLabel jLabelNombreAlbum1;
    private javax.swing.JLabel jLabelNombreAlbum2;
    private javax.swing.JLabel jLabelNombreAlbum3;
    private javax.swing.JLabel jLabelNombreAlbum4;
    // End of variables declaration//GEN-END:variables
}
