/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musictecplayer.vistas;

import java.awt.event.WindowEvent;
import musictecplayer.administradores.ReproductorLogico;
import musictecplayer.constantes.Parametros;

/**
 * @author Lucia Solis
 * @author Joseph Vega
 * @author Miller Ruiz
 */
public class Reproductor extends javax.swing.JFrame {

    private int estadoReproduccion = Parametros.DETENIDO;// 0 stop, 1 pausado, 2 reproduciendo
    private int tipoBusqueda = Parametros.ARTISTA;// 0 artista, 1 album, 2 genero,3 cancion 

    private String rutaCancionActual = "";

    private ReproductorLogico reproductor = null;

    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        initComponents();
        crearReproductor();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(WindowEvent winEvt) {

                if (reproductor != null) {
                    reproductor.stop();
                }

                System.exit(0);
            }
        });

    }

    public void crearReproductor() {
        reproductor = new ReproductorLogico();
        reproductor.stop();
    }

    private void escogerArchivo() {
        DetallesCancion DC = new DetallesCancion();
        this.disable();
        DC.show();
    }

    public void reubicarControles() {
        System.out.println("Reubicar");
        int cambioY = 480; //500
        int cambioX = 40; //390
        jLabelAnterior.setLocation(cambioX + 2, cambioY + 2);
        jLabelStop.setLocation(cambioX + 46, cambioY + 0);
        jLabelPlay.setLocation(cambioX + 94, cambioY + 2);
        jLabelAleatorio.setLocation(cambioX + 142, cambioY + 2);
        jLabelSiguiente.setLocation(cambioX + 190, cambioY + 2);

        jSliderPosicionCancion.setLocation(cambioX + 3, cambioY - 23);
        jLabelFondoAlbun1.setLocation(cambioX + 3, cambioY - 80);

        jLabelFondoAlbun2.setLocation(cambioX + 3, cambioY - 130);
        jLabelFondoAlbun3.setLocation(cambioX + 3, cambioY - 180);
        jLabelFondoAlbun.setLocation(cambioX + 13, cambioY - 170);
        jLabelFondoPlaylist.setLocation(cambioX - 5, cambioY - 340);
        jSliderVolumen.setLocation(cambioX + 201, cambioY - 150);
        jLabelVolumen.setLocation(cambioX + 200, cambioY - 60);

//        System.out.println(jLabelFondoPlaylist.getLocation().toString());
//        System.out.println(jLabelStop.getLocation().toString());
//        System.out.println(jLabelPlay.getLocation().toString());
//        System.out.println(jLabelAleatorio.getLocation().toString());
//        System.out.println(jLabelSiguiente.getLocation().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlaylist = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jLabelFondoMenu = new javax.swing.JLabel();
        jLabelFondoPlaylist = new javax.swing.JLabel();
        jSliderPosicionCancion = new javax.swing.JSlider();
        jSliderVolumen = new javax.swing.JSlider();
        jLabelVolumen = new javax.swing.JLabel();
        jLabelFondoAlbun = new javax.swing.JLabel();
        jLabelFondoAlbun1 = new javax.swing.JLabel();
        jLabelFondoAlbun2 = new javax.swing.JLabel();
        jLabelFondoAlbun3 = new javax.swing.JLabel();
        jLabelCambiarTipo = new javax.swing.JLabel();
        jLabelTipoBusqueda = new javax.swing.JLabel();
        jLabelFondoTipo = new javax.swing.JLabel();
        jLabelIconoBuscar = new javax.swing.JLabel();
        jTextFieldTextoBusqueda = new javax.swing.JTextField();
        jLabelBarraBusqueda = new javax.swing.JLabel();
        jLabelAnterior = new javax.swing.JLabel();
        jLabelAleatorio = new javax.swing.JLabel();
        jLabelStop = new javax.swing.JLabel();
        jLabelSiguiente = new javax.swing.JLabel();
        jLabelPlay = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelFondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(643, 569));
        setMinimumSize(new java.awt.Dimension(643, 569));
        setPreferredSize(new java.awt.Dimension(643, 569));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelPlaylist.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPlaylist.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaylist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaylist.setText("Lista de Reproducción");
        getContentPane().add(jLabelPlaylist);
        jLabelPlaylist.setBounds(40, 150, 230, 21);

        jLabelMenu.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setText("Agregar");
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(42, 39, 120, 50);

        jLabelFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/tipoBusqueda.fw.png"))); // NOI18N
        jLabelFondoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelFondoMenu);
        jLabelFondoMenu.setBounds(40, 40, 120, 50);

        jLabelFondoPlaylist.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondoPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoPlayList.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondoPlaylist);
        jLabelFondoPlaylist.setBounds(35, 140, 246, 146);

        jSliderPosicionCancion.setOpaque(false);
        getContentPane().add(jSliderPosicionCancion);
        jSliderPosicionCancion.setBounds(43, 457, 228, 23);

        jSliderVolumen.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderVolumen.setToolTipText("");
        jSliderVolumen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSliderVolumen.setOpaque(false);
        getContentPane().add(jSliderVolumen);
        jSliderVolumen.setBounds(241, 330, 10, 90);

        jLabelVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/volumenSinFondo.fw.png"))); // NOI18N
        getContentPane().add(jLabelVolumen);
        jLabelVolumen.setBounds(240, 420, 20, 30);

        jLabelFondoAlbun.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondoAlbun.setOpaque(true);
        getContentPane().add(jLabelFondoAlbun);
        jLabelFondoAlbun.setBounds(53, 310, 210, 140);

        jLabelFondoAlbun1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondoAlbun1);
        jLabelFondoAlbun1.setBounds(43, 400, 230, 57);

        jLabelFondoAlbun2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondoAlbun2);
        jLabelFondoAlbun2.setBounds(43, 350, 230, 57);

        jLabelFondoAlbun3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoOscuroAlbum.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondoAlbun3);
        jLabelFondoAlbun3.setBounds(43, 300, 230, 57);

        jLabelCambiarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/cambiarTipoBusqueda.fw.png"))); // NOI18N
        jLabelCambiarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCambiarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCambiarTipoMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelCambiarTipo);
        jLabelCambiarTipo.setBounds(325, 40, 61, 56);

        jLabelTipoBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTipoBusqueda.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelTipoBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoBusqueda.setText("Artista");
        getContentPane().add(jLabelTipoBusqueda);
        jLabelTipoBusqueda.setBounds(260, 58, 70, 21);

        jLabelFondoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/tipoBusqueda.fw.png"))); // NOI18N
        jLabelFondoTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelFondoTipo);
        jLabelFondoTipo.setBounds(258, 40, 70, 56);

        jLabelIconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/iconobuscar.fw.png"))); // NOI18N
        jLabelIconoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabelIconoBuscar);
        jLabelIconoBuscar.setBounds(410, 55, 23, 26);

        jTextFieldTextoBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldTextoBusqueda.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextFieldTextoBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTextoBusqueda.setBorder(null);
        jTextFieldTextoBusqueda.setOpaque(false);
        getContentPane().add(jTextFieldTextoBusqueda);
        jTextFieldTextoBusqueda.setBounds(440, 50, 160, 30);

        jLabelBarraBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/buscar.fw.png"))); // NOI18N
        getContentPane().add(jLabelBarraBusqueda);
        jLabelBarraBusqueda.setBounds(390, 40, 234, 56);

        jLabelAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/anterior.fw.png"))); // NOI18N
        jLabelAnterior.setToolTipText("Anterior");
        jLabelAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAnteriorMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAnterior);
        jLabelAnterior.setBounds(42, 482, 44, 56);

        jLabelAleatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/aleatorio.fw.png"))); // NOI18N
        jLabelAleatorio.setToolTipText("Reproducir");
        jLabelAleatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAleatorioMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAleatorio);
        jLabelAleatorio.setBounds(182, 482, 48, 56);

        jLabelStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/stop.fw.png"))); // NOI18N
        jLabelStop.setToolTipText("Detener");
        jLabelStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelStopMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelStop);
        jLabelStop.setBounds(86, 480, 48, 59);

        jLabelSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/siguiente.fw.png"))); // NOI18N
        jLabelSiguiente.setToolTipText("Siguiente");
        jLabelSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelSiguienteMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelSiguiente);
        jLabelSiguiente.setBounds(230, 482, 45, 56);

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/play.fw.png"))); // NOI18N
        jLabelPlay.setToolTipText("Reproducir");
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPlay);
        jLabelPlay.setBounds(134, 482, 48, 56);

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoReproductorV2.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(10, 0, 624, 560);

        jLabelFondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondoPrincipal);
        jLabelFondoPrincipal.setBounds(0, 0, 660, 590);

        setSize(new java.awt.Dimension(659, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAleatorioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAleatorioMouseReleased
        // TODO add your handling code here
        System.out.println("Aleatorio");


    }//GEN-LAST:event_jLabelAleatorioMouseReleased

    private void jLabelStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStopMouseReleased
        // TODO add your handling code here:
        System.out.println("Stop");

        reproductor.stop();
    }//GEN-LAST:event_jLabelStopMouseReleased

    private void jLabelAnteriorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnteriorMouseReleased
        // TODO add your handling code here:
        System.out.println("Anterior");
    }//GEN-LAST:event_jLabelAnteriorMouseReleased

    private void jLabelSiguienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteMouseReleased
        // TODO add your handling code here:
        System.out.println("Siguiente");
    }//GEN-LAST:event_jLabelSiguienteMouseReleased

    private void jLabelCambiarTipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCambiarTipoMouseReleased
        // TODO add your handling code here:
        if (tipoBusqueda == Parametros.ARTISTA) {
            tipoBusqueda = Parametros.ALBUM;
            jLabelTipoBusqueda.setText("Álbum");
        } else if (tipoBusqueda == Parametros.ALBUM) {
            tipoBusqueda = Parametros.GENERO;
            jLabelTipoBusqueda.setText("Género");
        } else if (tipoBusqueda == Parametros.GENERO) {
            tipoBusqueda = Parametros.CANCION;
            jLabelTipoBusqueda.setText("Canción");
        } else if (tipoBusqueda == Parametros.CANCION) {
            tipoBusqueda = Parametros.ARTISTA;
            jLabelTipoBusqueda.setText("Artista");
        }
    }//GEN-LAST:event_jLabelCambiarTipoMouseReleased

    private void jLabelPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseReleased
        // TODO add your handling code here:

        if (!rutaCancionActual.equals("")) {

            if (estadoReproduccion == Parametros.DETENIDO) {
                estadoReproduccion = Parametros.REPRODUCIENDO;
                System.out.println("D-Reproducir");
                jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/pause.fw.png"))); // NOI18N

                reproductor.play(rutaCancionActual);

            } else if (estadoReproduccion == Parametros.PAUSADO) {
                System.out.println("P-Reproducir");
                estadoReproduccion = Parametros.REPRODUCIENDO;
                jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/pause.fw.png"))); // NOI18N

                reproductor.resume();

            } else if (estadoReproduccion == Parametros.REPRODUCIENDO) {
                estadoReproduccion = Parametros.PAUSADO;
                System.out.println("R-Pausar");
                jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/play.fw.png"))); // NOI18N

                reproductor.pause();
            }
        }
    }//GEN-LAST:event_jLabelPlayMouseReleased

    private void jLabelMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseReleased
        escogerArchivo();
    }//GEN-LAST:event_jLabelMenuMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Reproductor().setVisible(true);
                Reproductor reproductor = new Reproductor();
                reproductor.reubicarControles();
                reproductor.setVisible(true);
                reproductor.repaint();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAleatorio;
    private javax.swing.JLabel jLabelAnterior;
    private javax.swing.JLabel jLabelBarraBusqueda;
    private javax.swing.JLabel jLabelCambiarTipo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoAlbun;
    private javax.swing.JLabel jLabelFondoAlbun1;
    private javax.swing.JLabel jLabelFondoAlbun2;
    private javax.swing.JLabel jLabelFondoAlbun3;
    private javax.swing.JLabel jLabelFondoMenu;
    private javax.swing.JLabel jLabelFondoPlaylist;
    private javax.swing.JLabel jLabelFondoPrincipal;
    private javax.swing.JLabel jLabelFondoTipo;
    private javax.swing.JLabel jLabelIconoBuscar;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelPlaylist;
    private javax.swing.JLabel jLabelSiguiente;
    private javax.swing.JLabel jLabelStop;
    private javax.swing.JLabel jLabelTipoBusqueda;
    private javax.swing.JLabel jLabelVolumen;
    private javax.swing.JSlider jSliderPosicionCancion;
    private javax.swing.JSlider jSliderVolumen;
    private javax.swing.JTextField jTextFieldTextoBusqueda;
    // End of variables declaration//GEN-END:variables
}
