/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musictecplayer.vistas;

import musictecplayer.constantes.Parametros;

/**
 *
 * @author Lucia
 */
public class Reproductor extends javax.swing.JFrame {

    private int estadoReproduccion = 0;// 0 stop, 1 pausado, 2 reproduciendo
    private int tipoBusqueda = 0;// 0 artista, 1 album, 2 genero,3 cancion 

    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        initComponents();

    }

    public void reubicarControles() {
        System.out.println("Reubicar");
        int cambioY = 500;
        int cambioX = 435;
        jLabelAnterior.setLocation(cambioX + 0, cambioY + 2);
        jLabelStop.setLocation(cambioX + 44, cambioY + 0);
        jLabelPlay.setLocation(cambioX + 92, cambioY + 2);
        jLabelSiguiente.setLocation(cambioX + 140, cambioY + 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCambiarTipo = new javax.swing.JLabel();
        jLabelTipoBusqueda = new javax.swing.JLabel();
        jLabelFondoTipo = new javax.swing.JLabel();
        jLabelIconoBuscar = new javax.swing.JLabel();
        jTextFieldTextoBusqueda = new javax.swing.JTextField();
        jLabelBarraBusqueda = new javax.swing.JLabel();
        jLabelAnterior = new javax.swing.JLabel();
        jLabelPlay = new javax.swing.JLabel();
        jLabelStop = new javax.swing.JLabel();
        jLabelSiguiente = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelFondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(670, 600));
        getContentPane().setLayout(null);

        jLabelCambiarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/cambiarTipoBusqueda.fw.png"))); // NOI18N
        jLabelCambiarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCambiarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCambiarTipoMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelCambiarTipo);
        jLabelCambiarTipo.setBounds(195, 40, 61, 56);

        jLabelTipoBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTipoBusqueda.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelTipoBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoBusqueda.setText("Artista");
        getContentPane().add(jLabelTipoBusqueda);
        jLabelTipoBusqueda.setBounds(280, 55, 90, 21);

        jLabelFondoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/tipoBusqueda.fw.png"))); // NOI18N
        jLabelFondoTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelFondoTipo);
        jLabelFondoTipo.setBounds(262, 40, 123, 56);

        jLabelIconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/iconobuscar.fw.png"))); // NOI18N
        jLabelIconoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabelIconoBuscar);
        jLabelIconoBuscar.setBounds(410, 55, 23, 26);

        jTextFieldTextoBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldTextoBusqueda.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextFieldTextoBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTextoBusqueda.setBorder(null);
        jTextFieldTextoBusqueda.setOpaque(false);
        getContentPane().add(jTextFieldTextoBusqueda);
        jTextFieldTextoBusqueda.setBounds(440, 50, 160, 30);

        jLabelBarraBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/buscar.fw.png"))); // NOI18N
        getContentPane().add(jLabelBarraBusqueda);
        jLabelBarraBusqueda.setBounds(390, 40, 234, 56);

        jLabelAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/anterior.fw.png"))); // NOI18N
        jLabelAnterior.setToolTipText("Anterior");
        jLabelAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAnteriorMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelAnterior);
        jLabelAnterior.setBounds(440, 490, 44, 56);

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/play.fw.png"))); // NOI18N
        jLabelPlay.setToolTipText("Reproducir");
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPlay);
        jLabelPlay.setBounds(530, 500, 48, 56);

        jLabelStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/stop.fw.png"))); // NOI18N
        jLabelStop.setToolTipText("Detener");
        jLabelStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelStopMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelStop);
        jLabelStop.setBounds(480, 490, 48, 59);

        jLabelSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/siguiente.fw.png"))); // NOI18N
        jLabelSiguiente.setToolTipText("Siguiente");
        jLabelSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelSiguienteMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelSiguiente);
        jLabelSiguiente.setBounds(580, 490, 45, 56);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondoReproductor.fw.png"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(20, 20, 624, 560);

        jLabelFondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondoPrincipal);
        jLabelFondoPrincipal.setBounds(0, 0, 670, 600);

        setSize(new java.awt.Dimension(686, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseReleased
        // TODO add your handling code here:

        if (estadoReproduccion == Parametros.DETENIDO) {
            estadoReproduccion = Parametros.REPRODUCIENDO;
            System.out.println("D-Reproducir");
            jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/pause.fw.png"))); // NOI18N
        } else if (estadoReproduccion == Parametros.PAUSADO) {
            System.out.println("P-Reproducir");
            estadoReproduccion = Parametros.REPRODUCIENDO;
            jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/pause.fw.png"))); // NOI18N
        } else if (estadoReproduccion == Parametros.REPRODUCIENDO) {
            estadoReproduccion = Parametros.PAUSADO;
            System.out.println("R-Pausar");
            jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musictecplayer/vistas/img/play.fw.png"))); // NOI18N
        }
    }//GEN-LAST:event_jLabelPlayMouseReleased

    private void jLabelStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStopMouseReleased
        // TODO add your handling code here:
        System.out.println("Stop");
    }//GEN-LAST:event_jLabelStopMouseReleased

    private void jLabelAnteriorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnteriorMouseReleased
        // TODO add your handling code here:
        System.out.println("Anterior");
    }//GEN-LAST:event_jLabelAnteriorMouseReleased

    private void jLabelSiguienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiguienteMouseReleased
        // TODO add your handling code here:
        System.out.println("Siguiente");
    }//GEN-LAST:event_jLabelSiguienteMouseReleased

    private void jLabelCambiarTipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCambiarTipoMouseReleased
        // TODO add your handling code here:
        if (tipoBusqueda == Parametros.ARTISTA) {
            tipoBusqueda = Parametros.ALBUM;
            jLabelTipoBusqueda.setText("Álbum");
        } else if (tipoBusqueda == Parametros.ALBUM) {
            tipoBusqueda = Parametros.GENERO;
            jLabelTipoBusqueda.setText("Género");
        } else if (tipoBusqueda == Parametros.GENERO) {
            tipoBusqueda = Parametros.CANCION;
            jLabelTipoBusqueda.setText("Canción");
        } else if (tipoBusqueda == Parametros.CANCION) {
            tipoBusqueda = Parametros.ARTISTA;
            jLabelTipoBusqueda.setText("Artista");
        }
    }//GEN-LAST:event_jLabelCambiarTipoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Reproductor().setVisible(true);
                Reproductor reproductor = new Reproductor();
                reproductor.reubicarControles();
                reproductor.setVisible(true);
                reproductor.repaint();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnterior;
    private javax.swing.JLabel jLabelBarraBusqueda;
    private javax.swing.JLabel jLabelCambiarTipo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoPrincipal;
    private javax.swing.JLabel jLabelFondoTipo;
    private javax.swing.JLabel jLabelIconoBuscar;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelSiguiente;
    private javax.swing.JLabel jLabelStop;
    private javax.swing.JLabel jLabelTipoBusqueda;
    private javax.swing.JTextField jTextFieldTextoBusqueda;
    // End of variables declaration//GEN-END:variables
}
